version: '3.8'
services:
  db:
    container_name: lifestyle_db
    image: postgres:14.1-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@lifestyle.com
      - PGADMIN_DEFAULT_PASSWORD=kavinda123
    ports:
      - '3030:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
volumes:
  db:
    driver: local
  pgadmin:
    driver: local