version: '3.8'
services:
  db:
    container_name: lifestyle_db
    image: postgres:14.1-alpine
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: on-failure
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@lifestyle.com
      - PGADMIN_DEFAULT_PASSWORD=kavinda123
    ports:
      - '3030:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:20.0.1
    restart: always
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - '3031:8080'
    command: start-dev
volumes:
  db:
    driver: local
  pgadmin:
    driver: local